FROM mcr.microsoft.com/dotnet/sdk:5.0
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV ASPNETCORE_URLS=http://+:80
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
EXPOSE 80

WORKDIR /src
COPY ["Tests/Weknow.EventSource.Backbone.WebEventTest/Weknow.EventSource.Backbone.WebEventTest.csproj", "Tests/Weknow.EventSource.Backbone.WebEventTest/"]

RUN dotnet restore "Tests/Weknow.EventSource.Backbone.WebEventTest/Weknow.EventSource.Backbone.WebEventTest.csproj"
COPY . .
WORKDIR "/src/Tests/Weknow.EventSource.Backbone.WebEventTest"
RUN dotnet build --no-restore "Weknow.EventSource.Backbone.WebEventTest.csproj" -c $BUILD_CONFIGURATION

RUN echo "exec dotnet run --no-build --no-launch-profile -c $BUILD_CONFIGURATION --" > /entrypoint.sh

ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]